# Generated by ariadne-codegen on 2023-06-15 23:53
# Source: queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetC2s(BaseModel):
    top_c2s: "GetC2sTopC2s" = Field(alias="topC2s")


class GetC2sTopC2s(BaseModel):
    query_info: "GetC2sTopC2sQueryInfo" = Field(alias="queryInfo")
    c2s: List["GetC2sTopC2sC2s"]


class GetC2sTopC2sQueryInfo(BaseModel):
    results_available: int = Field(alias="resultsAvailable")
    results_limit: int = Field(alias="resultsLimit")


class GetC2sTopC2sC2s(BaseModel):
    c2_domains: List[Optional[str]]
    c2_ips: List[Optional[str]]
    hits: int
    payload: str
    pervasiveness: int
    source_ip: str


GetC2s.update_forward_refs()
GetC2sTopC2s.update_forward_refs()
GetC2sTopC2sQueryInfo.update_forward_refs()
GetC2sTopC2sC2s.update_forward_refs()
