# Generated by ariadne-codegen on 2023-08-03 15:11
# Source: schemas/schema.graphql

from .base_model import BaseModel


class SpectaQLOption(BaseModel):
    key: str
    value: str


SpectaQLOption.update_forward_refs()
