# Generated by ariadne-codegen on 2023-09-26 13:39
# Source: schemas/schema.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel, Upload


class SpectaQLOption(BaseModel):
    key: str
    value: str


class HTTPInput(BaseModel):
    user_agent: Optional[str] = Field(alias="userAgent", default=None)


class PayloadInput(BaseModel):
    protocol: Optional[str] = None


class PivotInput(BaseModel):
    file: Upload
    gnql: bool
    reverse: bool
    ignore_private: bool = Field(alias="ignorePrivate")
    ignore_flows: bool = Field(alias="ignoreFlows")


SpectaQLOption.model_rebuild()
HTTPInput.model_rebuild()
PayloadInput.model_rebuild()
PivotInput.model_rebuild()
