# Generated by ariadne-codegen on 2023-06-15 22:24
# Source: schemas/schema.graphql

from .base_model import BaseModel


class SpectaQLOption(BaseModel):
    key: str
    value: str


SpectaQLOption.update_forward_refs()
