---
name: Build
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
  release:
    types: [created]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Lint
        run: make lint
  build:
    if: github.event_name == 'pull_request'
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Build
        run: make build
      - name: Bump version
        run: make bump
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Add build and bump changes {Github Actions}"
  tag:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Write release version
        run: |
          CUSTOM_TAG=$(cat .bumpversion.cfg | grep "current_version =" | cut -d' ' -f3)
          echo Version: v$CUSTOM_TAG
          echo "CUSTOM_TAG=v$CUSTOM_TAG" >> $GITHUB_ENV
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
