---
name: Build
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Lint
        run: make lint
  build:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: make build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Matt Lehman
          author_email: matt@greynoise.io
          message: "Generated client updates"
          add: "src/greynoiselabs/**"
  publish:
    needs: build
    if: github.ref =='refs/heads/main'
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/greynoiselabs
    env:
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@master
      - name: Publish to PyPI
        run: make publish
