---
name: Build
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Lint
        run: make lint
  build:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: make build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Matt Lehman
          author_email: matt@greynoise.io
          message: "Generated client updates"
          add: "src/labs-graphql-client/**"
  pypi-publish:
    name: Upload release to PyPI
    needs: build
    if: github.ref =='refs/heads/main'
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/labs-graphql-client
    permissions:
      id-token: write # Allows the action to upload a release
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: make build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TWINE_PASSWORD }}
