---
name: Release
on: # yamllint disable-line rule:truthy
  release:
    types: [created]
jobs:
  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/greynoiselabs
    env:
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Publish to PyPI
        run: make publish
